apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-sc
  hostPath:
    path: /nfs/apps  # directory on the host
    type: DirectoryOrCreate