apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # base64 encoded "password"
  mysql-user: cm9vdA==              # base64 encoded "root"
  mysql-database: ZGVtb19kYg==      # base64 encoded "demo_db"