apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secret.rootPassword }}
  mysql-user: {{ .Values.secret.user }}
  mysql-database: {{ .Values.secret.database }}