apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: {{ .Values.service.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  type: {{ .Values.service.mysql.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.service.app.port }}
    targetPort: {{ .Values.app.port }}
  type: {{ .Values.service.app.type }}